-------------------------------------------------------------------------------
Test set: com.online.medicine.service.test.AddressServiceTest
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 3.577 s <<< FAILURE! - in com.online.medicine.service.test.AddressServiceTest
createAddressTest  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.online.medicine.entity.Medicine.carts references an unknown entity: java.util.Set
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.online.medicine.entity.Medicine.carts references an unknown entity: java.util.Set

updateAddressTest  Time elapsed: 0 s  <<< ERROR!
java.lang.IllegalStateException: Failed to load ApplicationContext
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.online.medicine.entity.Medicine.carts references an unknown entity: java.util.Set
Caused by: org.hibernate.AnnotationException: @OneToOne or @ManyToOne on com.online.medicine.entity.Medicine.carts references an unknown entity: java.util.Set

